#! /bin/sh


NAME="./stuff/test_push_swap"
CHECKER="./checker_linux"
echo COMPILING ${NAME}
rm ${NAME}
make -C ../pushswap/
echo sdaf
mkdir -p ./stuff/
cp	../pushswap/push_swap ${NAME}
echo
echo EXECUTING ${NAME}


f_test ()
{
	echo "NUMBERS: ${1}"
	#${NAME} ${1} 
	echo "[[Lines: $(${NAME} $1 | wc -l)]]" 
	${NAME} ${1} | ${CHECKER} ${1}
	echo
}

f_test "0 1"
f_test "1 0"

f_test "0 1 2"
f_test "0 2 1"
f_test "1 0 2"
f_test "1 2 0"
f_test "2 0 1"
f_test "2 1 0"
